/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { SVGAssignData } from "./interfaces/interfaces";
export namespace Components {
    interface SvgRenderer {
        "selectorType": string;
        "skippableTags": Array<string>;
        "svg": string;
        "svgAssignDatas": Array<SVGAssignData<any>>;
    }
}
declare global {
    interface HTMLSvgRendererElement extends Components.SvgRenderer, HTMLStencilElement {
    }
    var HTMLSvgRendererElement: {
        prototype: HTMLSvgRendererElement;
        new (): HTMLSvgRendererElement;
    };
    interface HTMLElementTagNameMap {
        "svg-renderer": HTMLSvgRendererElement;
    }
}
declare namespace LocalJSX {
    interface SvgRenderer {
        "onElementClick"?: (event: CustomEvent<SVGSVGElement>) => void;
        "onImageAddedToSvg"?: (event: CustomEvent<any>) => void;
        "onRendered"?: (event: CustomEvent<SVGSVGElement>) => void;
        "onSvgFilled"?: (event: CustomEvent<SVGSVGElement>) => void;
        "selectorType"?: string;
        "skippableTags"?: Array<string>;
        "svg"?: string;
        "svgAssignDatas"?: Array<SVGAssignData<any>>;
    }
    interface IntrinsicElements {
        "svg-renderer": SvgRenderer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "svg-renderer": LocalJSX.SvgRenderer & JSXBase.HTMLAttributes<HTMLSvgRendererElement>;
        }
    }
}
